apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sm6hrxq30-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sm6hrxq30-go 
  name: sm6hrxq30-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: sm6hrxq30-go 
